@ECHO ON
REM ---PROGRAM TO DO AUTOMATICALLY TASM AND TLINK FOR YOUR ASM PROGRAM---

REM
REM ---VARIABILES---
SET PROG= %1

REM ---TASM---
TASM %PROG%.ASM

REM ---TLINK---
TLINK %PROG%

REM ---TEST PROGRAM---
REM POSSIBILITY TO CHOOSE DEBUG OR NOT
REM - UNCOMMENT THE ISTRUCTION YOU WOULD DO
REM - COMMENT THE ANOTHER ISTRUCTION

REM NO DEBUG
%PROG%.EXE				

REM DEBUG
REM DEBUG %PROG%.EXE

REM CHANGE DIR
REM MAKE SURE YOU HAVE SRC AND BIN FOLDERS
COPY %PROG%.ASM D:\SRC\%PROG%.ASM
COPY %PROG%.MAP D:\SRC\%PROG%.MAP
COPY %PROG%.OBJ D:\SRC\%PROG%.OBJ
COPY %PROG%.EXE D:\BIN\%PROG%.EXE

DEL %PROG%.ASM
DEL %PROG%.MAP
DEL %PROG%.OBJ
DEL %PROG%.EXE