@ECHO ON
REM ---PROGRAM TO DO AUTOMATICALLY TASM AND TLINK FOR YOUR ASM PROGRAM---

REM
REM ---VARIABILES---
SET PROG= %1

REM ---TASM---
TASM %PROG%.ASM

REM ---TLINK---
TLINK %PROG%

REM ---TEST PROGRAM---
REM POSSIBILITY TO CHOOSE DEBUG OR NOT
REM - UNCOMMENT THE ISTRUCTION YOU WOULD DO
REM - COMMENT THE ANOTHER ISTRUCTION

REM NO DEBUG
%PROG%.EXE				

REM DEBUG
REM DEBUG %PROG%.EXE	